
dotenv: .env
networks: 
  kovan:
    verified: True
  development:
    verified: False


wallets:
  from_key: 
    0: ${PRIVATE_KEY1}
    1: ${PRIVATE_KEY2} 
    2: ${PRIVATE_KEY3}
    3: ${PRIVATE_KEY4}
        